# Generated by Django 2.2.13 on 2020-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0074_add_word_limit_to_text_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningstatus',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
